package com.myspace.first;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class d11 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public d11() {
    }




}